export const INCREMENT = "INCREMENT";

export const DECREMENT = "DECREMENT";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";
export const USER_NOT_EXIST = "USER_NOT_EXIST";
